# Generated by Django 3.2.4 on 2021-08-14 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JointAccountModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.CharField(max_length=200, null=True)),
                ('available_balanace', models.CharField(max_length=200, null=True)),
                ('amount', models.IntegerField(null=True)),
                ('title', models.CharField(max_length=200, null=True)),
                ('description', models.TextField(null=True)),
            ],
        ),
    ]
