# Generated by Django 3.2.4 on 2021-08-14 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FinManApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jointaccountmodel',
            old_name='available_balanace',
            new_name='available_balance',
        ),
    ]
