# Generated by Django 3.2.4 on 2021-08-14 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinManApp', '0002_rename_available_balanace_jointaccountmodel_available_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSBAccountModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.CharField(max_length=200, null=True)),
                ('available_balance', models.CharField(max_length=200, null=True)),
                ('amount', models.IntegerField(null=True)),
                ('title', models.CharField(max_length=200, null=True)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InHandModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.CharField(max_length=200, null=True)),
                ('available_balance', models.CharField(max_length=200, null=True)),
                ('amount', models.IntegerField(null=True)),
                ('title', models.CharField(max_length=200, null=True)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MyAccountModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.CharField(max_length=200, null=True)),
                ('available_balance', models.CharField(max_length=200, null=True)),
                ('amount', models.IntegerField(null=True)),
                ('title', models.CharField(max_length=200, null=True)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PensionAccountModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.CharField(max_length=200, null=True)),
                ('available_balance', models.CharField(max_length=200, null=True)),
                ('amount', models.IntegerField(null=True)),
                ('title', models.CharField(max_length=200, null=True)),
                ('description', models.TextField(null=True)),
            ],
        ),
    ]
