# Generated by Django 3.2.4 on 2021-08-15 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FinManApp', '0003_csbaccountmodel_inhandmodel_myaccountmodel_pensionaccountmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inhandmodel',
            old_name='amount',
            new_name='iamount',
        ),
        migrations.RenameField(
            model_name='inhandmodel',
            old_name='available_balance',
            new_name='iavailable_balance',
        ),
        migrations.RenameField(
            model_name='inhandmodel',
            old_name='date_time',
            new_name='idate_time',
        ),
        migrations.RenameField(
            model_name='inhandmodel',
            old_name='description',
            new_name='idescription',
        ),
        migrations.RenameField(
            model_name='inhandmodel',
            old_name='title',
            new_name='ititle',
        ),
    ]
