# Generated by Django 3.2.4 on 2021-08-15 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FinManApp', '0004_auto_20210815_0933'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inhandmodel',
            old_name='iamount',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='inhandmodel',
            old_name='iavailable_balance',
            new_name='available_balance',
        ),
        migrations.RenameField(
            model_name='inhandmodel',
            old_name='idate_time',
            new_name='date_time',
        ),
        migrations.RenameField(
            model_name='inhandmodel',
            old_name='idescription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='inhandmodel',
            old_name='ititle',
            new_name='title',
        ),
    ]
