# Generated by Django 3.2.4 on 2021-08-15 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinManApp', '0005_auto_20210815_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='jointaccountmodel',
            name='month',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='jointaccountmodel',
            name='year',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
