# Generated by Django 3.2.4 on 2021-08-15 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinManApp', '0006_auto_20210815_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='csbaccountmodel',
            name='month',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='csbaccountmodel',
            name='year',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='inhandmodel',
            name='month',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='inhandmodel',
            name='year',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='myaccountmodel',
            name='month',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='myaccountmodel',
            name='year',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='pensionaccountmodel',
            name='month',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='pensionaccountmodel',
            name='year',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
